# Generated by Django 5.2 on 2025-04-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='sodium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='sugar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='calorie_goal',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='carb_goal',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='fat_goal',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein_goal',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='sodium_goal',
            field=models.PositiveIntegerField(default=2300),
        ),
        migrations.AddField(
            model_name='profile',
            name='sugar_goal',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='water_goal',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
